apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: frps
data:
  frps.ini: |-
    [common]
    bind_port = 7000
    token=WXYeXd^u%d2L2BK@oqwv
    vhost_http_port = 80
    # 7777-7778 建立TCP连接，7779-7780 建立UDP连接
    allow_ports = 7777-7780
    log_level = info
