apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-tcp-microk8s-conf
  namespace: ingress
data:
  7000: "default/frps:7000"
  7777: "default/frps:7777"
  7778: "default/frps:7778"
  7779: "default/frps:7779"
  7780: "default/frps:7780"
