---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: terraria-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/ubuntu/terraria/world"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraria-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: terraria
  name: terraria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraria
  template:
    metadata:
      labels:
        app: terraria
    spec:
      volumes:
        - name: terraria-pv-storage
          persistentVolumeClaim:
            claimName: terraria-pv-claim
      containers:
      - name: terraria
        image: ryshe/terraria:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7777
        volumeMounts:
        - name: terraria-pv-storage
          mountPath: /root/.local/share/Terraria/Worlds